# originally derived from the Pages/Pelican GitLab
# template's CI config file

# https://pythonspeed.com/articles/alpine-docker-python/
image: python:3.11-rc-bullseye

# ----------------------------------------------------------
pages:
  stage: deploy
  script:
  # - python3 builds.py
  - bash build.sh
  artifacts:
    paths:
    - public/
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
