name: github pages

on:
  push:
    branches:
      - main
permissions:
  contents: write

jobs:
  build-deploy:
    name: Build and Deploy
    runs-on: ubuntu-22.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # remove this step entirely if your site is pre-built
      - name: Install and Build
        run: |
          python3 builds.py

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: public
          branch: gh-pages
